export type LangInfo = {
  langName: string
  mimes?: string[]
  mime?: string
  mode: string
  ext?: string[]
  weight?: number
  alias?: string[]
  file?: RegExp
}

export const langMaps = {
  apl: {
    langName: 'APL',
    mime: 'text/apl',
    mode: 'apl',
    ext: ['dyalog', 'apl'],
  },
  dyalog: {
    langName: 'APL',
    mime: 'text/apl',
    mode: 'apl',
    ext: ['dyalog', 'apl'],
  },
  pgp: {
    langName: 'PGP',
    mimes: [
      'application/pgp',
      'application/pgp-encrypted',
      'application/pgp-keys',
      'application/pgp-signature',
    ],
    mode: 'asciiarmor',
    ext: ['asc', 'pgp', 'sig'],
  },
  asciiarmor: {
    langName: 'PGP',
    mimes: [
      'application/pgp',
      'application/pgp-encrypted',
      'application/pgp-keys',
      'application/pgp-signature',
    ],
    mode: 'asciiarmor',
    ext: ['asc', 'pgp', 'sig'],
  },
  asc: {
    langName: 'PGP',
    mimes: [
      'application/pgp',
      'application/pgp-encrypted',
      'application/pgp-keys',
      'application/pgp-signature',
    ],
    mode: 'asciiarmor',
    ext: ['asc', 'pgp', 'sig'],
  },
  sig: {
    langName: 'SML',
    mime: 'text/x-sml',
    mode: 'mllike',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  'asn.1': {
    langName: 'ASN.1',
    mime: 'text/x-ttcn-asn',
    mode: 'asn.1',
    ext: ['asn', 'asn1'],
  },
  asn: {
    langName: 'ASN.1',
    mime: 'text/x-ttcn-asn',
    mode: 'asn.1',
    ext: ['asn', 'asn1'],
  },
  asn1: {
    langName: 'ASN.1',
    mime: 'text/x-ttcn-asn',
    mode: 'asn.1',
    ext: ['asn', 'asn1'],
  },
  asterisk: {
    langName: 'Asterisk',
    mime: 'text/x-asterisk',
    mode: 'asterisk',
  },
  brainfuck: {
    langName: 'Brainfuck',
    mime: 'text/x-brainfuck',
    mode: 'brainfuck',
    ext: ['b', 'bf'],
  },
  b: {
    langName: 'Brainfuck',
    mime: 'text/x-brainfuck',
    mode: 'brainfuck',
    ext: ['b', 'bf'],
  },
  bf: {
    langName: 'Brainfuck',
    mime: 'text/x-brainfuck',
    mode: 'brainfuck',
    ext: ['b', 'bf'],
  },
  c: {
    langName: 'C',
    weight: 10,
    mime: 'text/x-csrc',
    mode: 'clike',
    ext: ['c', 'h', 'ino'],
  },
  clike: {
    langName: 'Squirrel',
    mime: 'text/x-squirrel',
    mode: 'clike',
    ext: ['nut'],
  },
  h: {
    langName: 'C',
    weight: 10,
    mime: 'text/x-csrc',
    mode: 'clike',
    ext: ['c', 'h', 'ino'],
  },
  ino: {
    langName: 'C',
    weight: 10,
    mime: 'text/x-csrc',
    mode: 'clike',
    ext: ['c', 'h', 'ino'],
  },
  'c++': {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  cpp: {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  cc: {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  cxx: {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  hpp: {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  'h++': {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  hh: {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  hxx: {
    langName: 'C++',
    weight: 10,
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  cobol: {
    langName: 'Cobol',
    mime: 'text/x-cobol',
    mode: 'cobol',
    ext: ['cob', 'cpy'],
  },
  cob: {
    langName: 'Cobol',
    mime: 'text/x-cobol',
    mode: 'cobol',
    ext: ['cob', 'cpy'],
  },
  cpy: {
    langName: 'Cobol',
    mime: 'text/x-cobol',
    mode: 'cobol',
    ext: ['cob', 'cpy'],
  },
  'c#': {
    langName: 'C#',
    weight: 10,
    mime: 'text/x-csharp',
    mode: 'clike',
    ext: ['cs'],
    alias: ['csharp', 'cs'],
  },
  cs: {
    langName: 'C#',
    weight: 10,
    mime: 'text/x-csharp',
    mode: 'clike',
    ext: ['cs'],
    alias: ['csharp', 'cs'],
  },
  csharp: {
    langName: 'C#',
    weight: 10,
    mime: 'text/x-csharp',
    mode: 'clike',
    ext: ['cs'],
    alias: ['csharp', 'cs'],
  },
  clojure: {
    langName: 'edn',
    mime: 'application/edn',
    mode: 'clojure',
    ext: ['edn'],
  },
  clj: {
    langName: 'Clojure',
    weight: 18,
    mime: 'text/x-clojure',
    mode: 'clojure',
    ext: ['clj', 'cljc', 'cljx'],
  },
  cljc: {
    langName: 'Clojure',
    weight: 18,
    mime: 'text/x-clojure',
    mode: 'clojure',
    ext: ['clj', 'cljc', 'cljx'],
  },
  cljx: {
    langName: 'Clojure',
    weight: 18,
    mime: 'text/x-clojure',
    mode: 'clojure',
    ext: ['clj', 'cljc', 'cljx'],
  },
  clojurescript: {
    langName: 'ClojureScript',
    weight: 18,
    mime: 'text/x-clojurescript',
    mode: 'clojure',
    ext: ['cljs'],
  },
  cljs: {
    langName: 'ClojureScript',
    weight: 18,
    mime: 'text/x-clojurescript',
    mode: 'clojure',
    ext: ['cljs'],
  },
  css: {
    langName: 'CSS',
    mime: 'text/x-css',
    mode: 'css',
    ext: ['css'],
    weight: 10,
  },
  'closure stylesheets (gss)': {
    langName: 'Closure Stylesheets (GSS)',
    mime: 'text/x-gss',
    mode: 'css',
    ext: ['gss'],
  },
  scss: { langName: 'SCSS', mime: 'text/x-scss', mode: 'css', ext: ['scss'] },
  gss: {
    langName: 'Closure Stylesheets (GSS)',
    mime: 'text/x-gss',
    mode: 'css',
    ext: ['gss'],
  },
  cmake: {
    langName: 'CMake',
    mime: 'text/x-cmake',
    mode: 'cmake',
    ext: ['cmake', 'cmake.in'],
  },
  'cmake.in': {
    langName: 'CMake',
    mime: 'text/x-cmake',
    mode: 'cmake',
    ext: ['cmake', 'cmake.in'],
  },
  coffeescript: {
    langName: 'CoffeeScript',
    mimes: [
      'application/vnd.coffeescript',
      'text/coffeescript',
      'text/x-coffeescript',
    ],
    mode: 'coffeescript',
    ext: ['coffee'],
    alias: ['coffee', 'coffee-script'],
  },
  coffee: {
    langName: 'CoffeeScript',
    mimes: [
      'application/vnd.coffeescript',
      'text/coffeescript',
      'text/x-coffeescript',
    ],
    mode: 'coffeescript',
    ext: ['coffee'],
    alias: ['coffee', 'coffee-script'],
  },
  'coffee-script': {
    langName: 'CoffeeScript',
    mimes: [
      'application/vnd.coffeescript',
      'text/coffeescript',
      'text/x-coffeescript',
    ],
    mode: 'coffeescript',
    ext: ['coffee'],
    alias: ['coffee', 'coffee-script'],
  },
  'common lisp': {
    langName: 'Common Lisp',
    mime: 'text/x-common-lisp',
    mode: 'commonlisp',
    ext: ['cl', 'lisp', 'el'],
    alias: ['lisp'],
  },
  commonlisp: {
    langName: 'Common Lisp',
    mime: 'text/x-common-lisp',
    mode: 'commonlisp',
    ext: ['cl', 'lisp', 'el'],
    alias: ['lisp'],
  },
  cl: {
    langName: 'Common Lisp',
    mime: 'text/x-common-lisp',
    mode: 'commonlisp',
    ext: ['cl', 'lisp', 'el'],
    alias: ['lisp'],
  },
  lisp: {
    langName: 'Common Lisp',
    mime: 'text/x-common-lisp',
    mode: 'commonlisp',
    ext: ['cl', 'lisp', 'el'],
    alias: ['lisp'],
  },
  el: {
    langName: 'Common Lisp',
    mime: 'text/x-common-lisp',
    mode: 'commonlisp',
    ext: ['cl', 'lisp', 'el'],
    alias: ['lisp'],
  },
  cypher: {
    langName: 'Cypher',
    mime: 'application/x-cypher-query',
    mode: 'cypher',
    ext: ['cyp', 'cypher'],
  },
  cyp: {
    langName: 'Cypher',
    mime: 'application/x-cypher-query',
    mode: 'cypher',
    ext: ['cyp', 'cypher'],
  },
  python: {
    langName: 'Python',
    weight: 12,
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
  },
  cython: {
    langName: 'Cython',
    mime: 'text/x-cython',
    mode: 'python',
    ext: ['pyx', 'pxd', 'pxi'],
  },
  pyx: {
    langName: 'Cython',
    mime: 'text/x-cython',
    mode: 'python',
    ext: ['pyx', 'pxd', 'pxi'],
  },
  pxd: {
    langName: 'Cython',
    mime: 'text/x-cython',
    mode: 'python',
    ext: ['pyx', 'pxd', 'pxi'],
  },
  pxi: {
    langName: 'Cython',
    mime: 'text/x-cython',
    mode: 'python',
    ext: ['pyx', 'pxd', 'pxi'],
  },
  crystal: {
    langName: 'Crystal',
    mime: 'text/x-crystal',
    mode: 'crystal',
    ext: ['cr'],
  },
  cr: {
    langName: 'Crystal',
    mime: 'text/x-crystal',
    mode: 'crystal',
    ext: ['cr'],
  },
  cql: { langName: 'CQL', mime: 'text/x-cassandra', mode: 'sql', ext: ['cql'] },
  sql: { langName: 'SQLite', mime: 'text/x-sqlite', mode: 'sql' },
  d: { langName: 'D', mime: 'text/x-d', mode: 'd', ext: ['d'] },
  dart: {
    langName: 'Dart',
    weight: 19,
    mimes: ['application/dart', 'text/x-dart'],
    mode: 'dart',
    ext: ['dart'],
  },
  diff: {
    langName: 'diff',
    mime: 'text/x-diff',
    mode: 'diff',
    ext: ['diff', 'patch'],
  },
  patch: {
    langName: 'diff',
    mime: 'text/x-diff',
    mode: 'diff',
    ext: ['diff', 'patch'],
  },
  django: { langName: 'Django', mime: 'text/x-django', mode: 'django' },
  dockerfile: {
    langName: 'Dockerfile',
    mime: 'text/x-dockerfile',
    mode: 'dockerfile',
  },
  dtd: {
    langName: 'DTD',
    mime: 'application/xml-dtd',
    mode: 'dtd',
    ext: ['dtd'],
  },
  dylan: {
    langName: 'Dylan',
    mime: 'text/x-dylan',
    mode: 'dylan',
    ext: ['dylan', 'dyl', 'intr'],
  },
  dyl: {
    langName: 'Dylan',
    mime: 'text/x-dylan',
    mode: 'dylan',
    ext: ['dylan', 'dyl', 'intr'],
  },
  intr: {
    langName: 'Dylan',
    mime: 'text/x-dylan',
    mode: 'dylan',
    ext: ['dylan', 'dyl', 'intr'],
  },
  ebnf: { langName: 'EBNF', mime: 'text/x-ebnf', mode: 'ebnf' },
  ecl: { langName: 'ECL', mime: 'text/x-ecl', mode: 'ecl', ext: ['ecl'] },
  edn: {
    langName: 'edn',
    mime: 'application/edn',
    mode: 'clojure',
    ext: ['edn'],
  },
  eiffel: {
    langName: 'Eiffel',
    mime: 'text/x-eiffel',
    mode: 'eiffel',
    ext: ['e'],
  },
  e: { langName: 'Eiffel', mime: 'text/x-eiffel', mode: 'eiffel', ext: ['e'] },
  elm: { langName: 'Elm', mime: 'text/x-elm', mode: 'elm', ext: ['elm'] },
  'embedded javascript': {
    langName: 'Embedded Javascript',
    mime: 'application/x-ejs',
    mode: 'htmlembedded',
    ext: ['ejs'],
  },
  htmlembedded: {
    langName: 'Java Server Pages',
    mime: 'application/x-jsp',
    mode: 'htmlembedded',
    ext: ['jsp'],
    alias: ['jsp'],
  },
  ejs: {
    langName: 'Embedded Javascript',
    mime: 'application/x-ejs',
    mode: 'htmlembedded',
    ext: ['ejs'],
  },
  'embedded ruby': {
    langName: 'Embedded Ruby',
    mime: 'application/x-erb',
    mode: 'htmlembedded',
    ext: ['erb'],
  },
  erb: {
    langName: 'Embedded Ruby',
    mime: 'application/x-erb',
    mode: 'htmlembedded',
    ext: ['erb'],
  },
  erlang: {
    langName: 'Erlang',
    mime: 'text/x-erlang',
    mode: 'erlang',
    ext: ['erl'],
  },
  erl: {
    langName: 'Erlang',
    mime: 'text/x-erlang',
    mode: 'erlang',
    ext: ['erl'],
  },
  esper: { langName: 'Esper', mime: 'text/x-esper', mode: 'sql' },
  factor: {
    langName: 'Factor',
    mime: 'text/x-factor',
    mode: 'factor',
    ext: ['factor'],
  },
  fcl: { langName: 'FCL', mime: 'text/x-fcl', mode: 'fcl' },
  forth: {
    langName: 'Forth',
    mime: 'text/x-forth',
    mode: 'forth',
    ext: ['forth', 'fth', '4th'],
  },
  fth: {
    langName: 'Forth',
    mime: 'text/x-forth',
    mode: 'forth',
    ext: ['forth', 'fth', '4th'],
  },
  '4th': {
    langName: 'Forth',
    mime: 'text/x-forth',
    mode: 'forth',
    ext: ['forth', 'fth', '4th'],
  },
  fortran: {
    langName: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  f: {
    langName: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  for: {
    langName: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  f77: {
    langName: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  f90: {
    langName: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  f95: {
    langName: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  'f#': {
    langName: 'F#',
    mime: 'text/x-fsharp',
    mode: 'mllike',
    ext: ['fs'],
    alias: ['fsharp'],
  },
  mllike: {
    langName: 'SML',
    mime: 'text/x-sml',
    mode: 'mllike',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  fs: {
    langName: 'F#',
    mime: 'text/x-fsharp',
    mode: 'mllike',
    ext: ['fs'],
    alias: ['fsharp'],
  },
  fsharp: {
    langName: 'F#',
    mime: 'text/x-fsharp',
    mode: 'mllike',
    ext: ['fs'],
    alias: ['fsharp'],
  },
  gas: { langName: 'Gas', mime: 'text/x-gas', mode: 'gas', ext: ['s'] },
  s: { langName: 'Gas', mime: 'text/x-gas', mode: 'gas', ext: ['s'] },
  gherkin: {
    langName: 'Gherkin',
    mime: 'text/x-feature',
    mode: 'gherkin',
    ext: ['feature'],
  },
  feature: {
    langName: 'Gherkin',
    mime: 'text/x-feature',
    mode: 'gherkin',
    ext: ['feature'],
  },
  'github flavored markdown': {
    langName: 'GitHub Flavored Markdown',
    mime: 'text/x-gfm',
    mode: 'gfm',
  },
  gfm: {
    langName: 'GitHub Flavored Markdown',
    mime: 'text/x-gfm',
    mode: 'gfm',
  },
  go: {
    langName: 'Go',
    weight: 13,
    mime: 'text/x-go',
    mode: 'go',
    ext: ['go'],
  },
  groovy: {
    langName: 'Groovy',
    mime: 'text/x-groovy',
    mode: 'groovy',
    ext: ['groovy', 'gradle'],
  },
  gradle: {
    langName: 'Groovy',
    mime: 'text/x-groovy',
    mode: 'groovy',
    ext: ['groovy', 'gradle'],
  },
  haml: { langName: 'HAML', mime: 'text/x-haml', mode: 'haml', ext: ['haml'] },
  haskell: {
    langName: 'Haskell',
    mime: 'text/x-haskell',
    mode: 'haskell',
    ext: ['hs'],
  },
  hs: {
    langName: 'Haskell',
    mime: 'text/x-haskell',
    mode: 'haskell',
    ext: ['hs'],
  },
  'haskell (literate)': {
    langName: 'Haskell (Literate)',
    mime: 'text/x-literate-haskell',
    mode: 'haskell-literate',
    ext: ['lhs'],
  },
  'haskell-literate': {
    langName: 'Haskell (Literate)',
    mime: 'text/x-literate-haskell',
    mode: 'haskell-literate',
    ext: ['lhs'],
  },
  lhs: {
    langName: 'Haskell (Literate)',
    mime: 'text/x-literate-haskell',
    mode: 'haskell-literate',
    ext: ['lhs'],
  },
  haxe: { langName: 'HXML', mime: 'text/x-hxml', mode: 'haxe', ext: ['hxml'] },
  hx: { langName: 'Haxe', mime: 'text/x-haxe', mode: 'haxe', ext: ['hx'] },
  hxml: { langName: 'HXML', mime: 'text/x-hxml', mode: 'haxe', ext: ['hxml'] },
  'asp.net': {
    langName: 'ASP.NET',
    mime: 'application/x-aspx',
    mode: 'htmlembedded',
    ext: ['aspx'],
    alias: ['asp', 'aspx'],
  },
  aspx: {
    langName: 'ASP.NET',
    mime: 'application/x-aspx',
    mode: 'htmlembedded',
    ext: ['aspx'],
    alias: ['asp', 'aspx'],
  },
  asp: {
    langName: 'ASP.NET',
    mime: 'application/x-aspx',
    mode: 'htmlembedded',
    ext: ['aspx'],
    alias: ['asp', 'aspx'],
  },
  html: {
    langName: 'HTML',
    weight: 8,
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  htmlmixed: {
    langName: 'HTML',
    weight: 8,
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  htm: {
    langName: 'HTML',
    weight: 8,
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  handlebars: {
    langName: 'HTML',
    weight: 8,
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  hbs: {
    langName: 'HTML',
    weight: 8,
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  xhtml: {
    langName: 'HTML',
    weight: 8,
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  http: { langName: 'HTTP', mime: 'message/http', mode: 'http' },
  idl: { langName: 'IDL', mime: 'text/x-idl', mode: 'idl', ext: ['pro'] },
  pro: { langName: 'IDL', mime: 'text/x-idl', mode: 'idl', ext: ['pro'] },
  pug: {
    langName: 'Pug',
    mime: 'text/x-pug',
    mode: 'pug',
    ext: ['jade', 'pug'],
    alias: ['jade'],
  },
  jade: {
    langName: 'Pug',
    mime: 'text/x-pug',
    mode: 'pug',
    ext: ['jade', 'pug'],
    alias: ['jade'],
  },
  java: {
    langName: 'Java',
    weight: 12,
    mime: 'text/x-java',
    mode: 'clike',
    ext: ['java'],
  },
  'java server pages': {
    langName: 'Java Server Pages',
    mime: 'application/x-jsp',
    mode: 'htmlembedded',
    ext: ['jsp'],
    alias: ['jsp'],
  },
  jsp: {
    langName: 'Java Server Pages',
    mime: 'application/x-jsp',
    mode: 'htmlembedded',
    ext: ['jsp'],
    alias: ['jsp'],
  },
  javascript: {
    langName: 'TypeScript',
    weight: 10,
    mime: 'application/typescript',
    mode: 'javascript',
    ext: ['ts'],
    alias: ['ts'],
  },
  js: {
    langName: 'JavaScript',
    weight: 9,
    mimes: [
      'text/javascript',
      'text/ecmascript',
      'application/javascript',
      'application/x-javascript',
      'application/ecmascript',
    ],
    mode: 'javascript',
    ext: ['js'],
    alias: ['ecmascript', 'js', 'node'],
  },
  ecmascript: {
    langName: 'JavaScript',
    weight: 9,
    mimes: [
      'text/javascript',
      'text/ecmascript',
      'application/javascript',
      'application/x-javascript',
      'application/ecmascript',
    ],
    mode: 'javascript',
    ext: ['js'],
    alias: ['ecmascript', 'js', 'node'],
  },
  // node: {
  //   langName: 'JavaScript',
  //   weight: 9,
  //   mimes: [
  //     'text/javascript',
  //     'text/ecmascript',
  //     'application/javascript',
  //     'application/x-javascript',
  //     'application/ecmascript',
  //   ],
  //   mode: 'javascript',
  //   ext: ['js'],
  //   alias: ['ecmascript', 'js', 'node'],
  // },
  // json: {
  //   langName: 'JSON',
  //   mimes: ['application/json', 'application/x-json'],
  //   mode: 'javascript',
  //   ext: ['json', 'map'],
  //   alias: ['json5'],
  // },
  // map: {
  //   langName: 'JSON',
  //   mimes: ['application/json', 'application/x-json'],
  //   mode: 'javascript',
  //   ext: ['json', 'map'],
  //   alias: ['json5'],
  // },
  // json5: {
  //   langName: 'JSON',
  //   mimes: ['application/json', 'application/x-json'],
  //   mode: 'javascript',
  //   ext: ['json', 'map'],
  //   alias: ['json5'],
  // },
  // 'json-ld': {
  //   langName: 'JSON-LD',
  //   mime: 'application/ld+json',
  //   mode: 'javascript',
  //   ext: ['jsonld'],
  //   alias: ['jsonld'],
  // },
  jsonld: { langName: 'PEG.js', mime: 'null', mode: 'pegjs', ext: ['jsonld'] },
  jsx: {
    langName: 'TypeScript-JSX',
    mime: 'text/typescript-jsx',
    mode: 'jsx',
    ext: ['tsx'],
    alias: ['tsx'],
  },
  jinja2: {
    langName: 'Jinja2',
    mime: 'text/jinja2',
    mode: 'jinja2',
    ext: ['j2', 'jinja', 'jinja2'],
  },
  j2: {
    langName: 'Jinja2',
    mime: 'text/jinja2',
    mode: 'jinja2',
    ext: ['j2', 'jinja', 'jinja2'],
  },
  jinja: {
    langName: 'Jinja2',
    mime: 'text/jinja2',
    mode: 'jinja2',
    ext: ['j2', 'jinja', 'jinja2'],
  },
  julia: {
    langName: 'Julia',
    mime: 'text/x-julia',
    mode: 'julia',
    ext: ['jl'],
  },
  jl: { langName: 'Julia', mime: 'text/x-julia', mode: 'julia', ext: ['jl'] },
  kotlin: {
    langName: 'Kotlin',
    mime: 'text/x-kotlin',
    mode: 'clike',
    ext: ['kt'],
  },
  kt: { langName: 'Kotlin', mime: 'text/x-kotlin', mode: 'clike', ext: ['kt'] },
  less: { langName: 'LESS', mime: 'text/x-less', mode: 'css', ext: ['less'] },
  livescript: {
    langName: 'LiveScript',
    mime: 'text/x-livescript',
    mode: 'livescript',
    ext: ['ls'],
    alias: ['ls'],
  },
  ls: {
    langName: 'LiveScript',
    mime: 'text/x-livescript',
    mode: 'livescript',
    ext: ['ls'],
    alias: ['ls'],
  },
  lua: {
    langName: 'Lua',
    weight: 15,
    mime: 'text/x-lua',
    mode: 'lua',
    ext: ['lua'],
  },
  txt: {
    langName: 'Plain text',
    mime: 'text/plain',
    mode: 'markdown',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  md: {
    langName: 'Markdown',
    weight: 7,
    mime: 'text/x-markdown',
    mode: 'markdown',
    ext: ['markdown', 'md', 'mkd'],
  },
  // mkd: {
  //   langName: 'Markdown',
  //   weight: 7,
  //   mime: 'text/x-markdown',
  //   mode: 'markdown',
  //   ext: ['markdown', 'md', 'mkd'],
  // },
  mirc: { langName: 'mIRC', mime: 'text/mirc', mode: 'mirc' },
  // 'mariadb sql': { langName: 'MariaDB SQL', mime: 'text/x-mariadb', mode: 'sql' },
  mathematica: {
    langName: 'Mathematica',
    mime: 'text/x-mathematica',
    mode: 'mathematica',
    ext: ['m', 'nb', 'wl', 'wls'],
  },
  m: { langName: 'Octave', mime: 'text/x-octave', mode: 'octave', ext: ['m'] },
  nb: {
    langName: 'Mathematica',
    mime: 'text/x-mathematica',
    mode: 'mathematica',
    ext: ['m', 'nb', 'wl', 'wls'],
  },
  wl: {
    langName: 'Mathematica',
    mime: 'text/x-mathematica',
    mode: 'mathematica',
    ext: ['m', 'nb', 'wl', 'wls'],
  },
  wls: {
    langName: 'Mathematica',
    mime: 'text/x-mathematica',
    mode: 'mathematica',
    ext: ['m', 'nb', 'wl', 'wls'],
  },
  modelica: {
    langName: 'Modelica',
    mime: 'text/x-modelica',
    mode: 'modelica',
    ext: ['mo'],
  },
  mo: {
    langName: 'Modelica',
    mime: 'text/x-modelica',
    mode: 'modelica',
    ext: ['mo'],
  },
  mumps: {
    langName: 'MUMPS',
    mime: 'text/x-mumps',
    mode: 'mumps',
    ext: ['mps'],
  },
  mps: { langName: 'MUMPS', mime: 'text/x-mumps', mode: 'mumps', ext: ['mps'] },
  'ms sql': { langName: 'MS SQL', mime: 'text/x-mssql', mode: 'sql' },
  mbox: {
    langName: 'mbox',
    mime: 'application/mbox',
    mode: 'mbox',
    ext: ['mbox'],
  },
  mysql: { langName: 'MySQL', weight: 20, mime: 'text/x-mysql', mode: 'sql' },
  nginx: { langName: 'Nginx', mime: 'text/x-nginx-conf', mode: 'nginx' },
  nsis: {
    langName: 'NSIS',
    mime: 'text/x-nsis',
    mode: 'nsis',
    ext: ['nsh', 'nsi'],
  },
  nsh: {
    langName: 'NSIS',
    mime: 'text/x-nsis',
    mode: 'nsis',
    ext: ['nsh', 'nsi'],
  },
  nsi: {
    langName: 'NSIS',
    mime: 'text/x-nsis',
    mode: 'nsis',
    ext: ['nsh', 'nsi'],
  },
  ntriples: {
    langName: 'NTriples',
    mimes: ['application/n-triples', 'application/n-quads', 'text/n-triples'],
    mode: 'ntriples',
    ext: ['nt', 'nq'],
  },
  nt: {
    langName: 'NTriples',
    mimes: ['application/n-triples', 'application/n-quads', 'text/n-triples'],
    mode: 'ntriples',
    ext: ['nt', 'nq'],
  },
  nq: {
    langName: 'NTriples',
    mimes: ['application/n-triples', 'application/n-quads', 'text/n-triples'],
    mode: 'ntriples',
    ext: ['nt', 'nq'],
  },
  'objective-c': {
    langName: 'Objective C',
    weight: 11,
    mime: 'text/x-objectivec',
    mode: 'clike',
    ext: ['m'],
    alias: ['objective-c', 'objc'],
  },
  objc: {
    langName: 'Objective C',
    weight: 11,
    mime: 'text/x-objectivec',
    mode: 'clike',
    ext: ['m'],
    alias: ['objective-c', 'objc'],
  },
  'objective-c++': {
    langName: 'Objective C++',
    mime: 'text/x-objectivec++',
    mode: 'clike',
    weight: 11,
    ext: ['mm'],
    alias: ['objective-c++', 'objc++'],
  },
  mm: {
    langName: 'Objective C++',
    weight: 11,
    mime: 'text/x-objectivec++',
    mode: 'clike',
    ext: ['mm'],
    alias: ['objective-c++', 'objc++'],
  },
  'objc++': {
    langName: 'Objective C++',
    mime: 'text/x-objectivec++',
    mode: 'clike',
    ext: ['mm'],
    alias: ['objective-c++', 'objc++'],
  },
  ocaml: {
    langName: 'OCaml',
    mime: 'text/x-ocaml',
    mode: 'mllike',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  ml: {
    langName: 'OCaml',
    mime: 'text/x-ocaml',
    mode: 'mllike',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  mli: {
    langName: 'OCaml',
    mime: 'text/x-ocaml',
    mode: 'mllike',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  mll: {
    langName: 'OCaml',
    mime: 'text/x-ocaml',
    mode: 'mllike',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  mly: {
    langName: 'OCaml',
    mime: 'text/x-ocaml',
    mode: 'mllike',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  octave: {
    langName: 'Octave',
    mime: 'text/x-octave',
    mode: 'octave',
    ext: ['m'],
  },
  oz: { langName: 'Oz', mime: 'text/x-oz', mode: 'oz', ext: ['oz'] },
  pascal: {
    langName: 'Pascal',
    mime: 'text/x-pascal',
    mode: 'pascal',
    ext: ['p', 'pas'],
  },
  p: {
    langName: 'Pascal',
    mime: 'text/x-pascal',
    mode: 'pascal',
    ext: ['p', 'pas'],
  },
  pas: {
    langName: 'Pascal',
    mime: 'text/x-pascal',
    mode: 'pascal',
    ext: ['p', 'pas'],
  },
  'peg.js': {
    langName: 'PEG.js',
    mime: 'null',
    mode: 'pegjs',
    ext: ['jsonld'],
  },
  pegjs: { langName: 'PEG.js', mime: 'null', mode: 'pegjs', ext: ['jsonld'] },
  perl: {
    langName: 'Perl',
    mime: 'text/x-perl',
    mode: 'perl',
    ext: ['pl', 'pm'],
  },
  pl: {
    langName: 'Perl',
    mime: 'text/x-perl',
    mode: 'perl',
    ext: ['pl', 'pm'],
  },
  pm: {
    langName: 'Perl',
    mime: 'text/x-perl',
    mode: 'perl',
    ext: ['pl', 'pm'],
  },
  php: {
    langName: 'PHP',
    weight: 11,
    mimes: [
      'text/x-php',
      'application/x-httpd-php',
      'application/x-httpd-php-open',
    ],
    mode: 'php',
    ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  },
  // php3: {
  //   langName: 'PHP',
  //   weight: 11,
  //   mimes: [
  //     'text/x-php',
  //     'application/x-httpd-php',
  //     'application/x-httpd-php-open',
  //   ],
  //   mode: 'php',
  //   ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  // },
  // php4: {
  //   langName: 'PHP',
  //   weight: 11,
  //   mimes: [
  //     'text/x-php',
  //     'application/x-httpd-php',
  //     'application/x-httpd-php-open',
  //   ],
  //   mode: 'php',
  //   ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  // },
  // php5: {
  //   langName: 'PHP',
  //   weight: 11,
  //   mimes: [
  //     'text/x-php',
  //     'application/x-httpd-php',
  //     'application/x-httpd-php-open',
  //   ],
  //   mode: 'php',
  //   ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  // },
  // php7: {
  //   langName: 'PHP',
  //   weight: 11,
  //   mimes: [
  //     'text/x-php',
  //     'application/x-httpd-php',
  //     'application/x-httpd-php-open',
  //   ],
  //   mode: 'php',
  //   ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  // },
  phtml: {
    langName: 'PHP',
    weight: 11,
    mimes: [
      'text/x-php',
      'application/x-httpd-php',
      'application/x-httpd-php-open',
    ],
    mode: 'php',
    ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  },
  pig: { langName: 'Pig', mime: 'text/x-pig', mode: 'pig', ext: ['pig'] },
  'plain text': {
    langName: 'Plain Text',
    mime: 'text/plain',
    mode: 'markdown',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  text: {
    langName: 'LaTeX',
    weight: 10,
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  conf: {
    langName: 'Plain Text',
    mime: 'text/plain',
    mode: 'markdown',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  def: {
    langName: 'Plain Text',
    mime: 'text/plain',
    mode: 'markdown',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  list: {
    langName: 'Plain Text',
    mime: 'text/plain',
    mode: 'markdown',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  log: {
    langName: 'Plain Text',
    mime: 'text/plain',
    mode: 'markdown',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  plsql: { langName: 'PLSQL', mime: 'text/x-plsql', mode: 'sql', ext: ['pls'] },
  pls: { langName: 'PLSQL', mime: 'text/x-plsql', mode: 'sql', ext: ['pls'] },
  postgresql: { langName: 'PostgreSQL', mime: 'text/x-pgsql', mode: 'sql' },
  powershell: {
    langName: 'PowerShell',
    mime: 'application/x-powershell',
    mode: 'powershell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  ps1: {
    langName: 'PowerShell',
    mime: 'application/x-powershell',
    mode: 'powershell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  psd1: {
    langName: 'PowerShell',
    mime: 'application/x-powershell',
    mode: 'powershell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  psm1: {
    langName: 'PowerShell',
    mime: 'application/x-powershell',
    mode: 'powershell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  'properties files': {
    langName: 'Properties files',
    mime: 'text/x-properties',
    mode: 'properties',
    ext: ['properties', 'ini', 'in'],
    alias: ['ini', 'properties'],
  },
  properties: {
    langName: 'Properties files',
    mime: 'text/x-properties',
    mode: 'properties',
    ext: ['properties', 'ini', 'in'],
    alias: ['ini', 'properties'],
  },
  ini: {
    langName: 'Properties files',
    mime: 'text/x-properties',
    mode: 'properties',
    ext: ['properties', 'ini', 'in'],
    alias: ['ini', 'properties'],
  },
  in: {
    langName: 'Properties files',
    mime: 'text/x-properties',
    mode: 'properties',
    ext: ['properties', 'ini', 'in'],
    alias: ['ini', 'properties'],
  },
  protobuf: {
    langName: 'ProtoBuf',
    mime: 'text/x-protobuf',
    mode: 'protobuf',
    ext: ['proto'],
  },
  proto: {
    langName: 'ProtoBuf',
    mime: 'text/x-protobuf',
    mode: 'protobuf',
    ext: ['proto'],
  },
  BUILD: {
    langName: 'Python',
    weight: 12,
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
  },
  bzl: {
    langName: 'Python',
    weight: 12,
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
  },
  py: {
    langName: 'Python',
    weight: 12,
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
  },
  pyw: {
    langName: 'Python',
    weight: 12,
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
  },
  puppet: {
    langName: 'Puppet',
    mime: 'text/x-puppet',
    mode: 'puppet',
    ext: ['pp'],
  },
  pp: {
    langName: 'Puppet',
    mime: 'text/x-puppet',
    mode: 'puppet',
    ext: ['pp'],
  },
  q: { langName: 'Q', mime: 'text/x-q', mode: 'q', ext: ['q'] },
  r: {
    langName: 'R',
    mime: 'text/x-rsrc',
    mode: 'r',
    ext: ['r', 'R'],
    alias: ['rscript'],
  },
  R: {
    langName: 'R',
    mime: 'text/x-rsrc',
    mode: 'r',
    ext: ['r', 'R'],
    alias: ['rscript'],
  },
  rscript: {
    langName: 'R',
    mime: 'text/x-rsrc',
    mode: 'r',
    ext: ['r', 'R'],
    alias: ['rscript'],
  },
  restructuredtext: {
    langName: 'reStructuredText',
    mime: 'text/x-rst',
    mode: 'rst',
    ext: ['rst'],
    alias: ['rst'],
  },
  rst: {
    langName: 'reStructuredText',
    mime: 'text/x-rst',
    mode: 'rst',
    ext: ['rst'],
    alias: ['rst'],
  },
  'rpm changes': {
    langName: 'RPM Changes',
    mime: 'text/x-rpm-changes',
    mode: 'rpm',
  },
  rpm: {
    langName: 'RPM Spec',
    mime: 'text/x-rpm-spec',
    mode: 'rpm',
    ext: ['spec'],
  },
  'rpm spec': {
    langName: 'RPM Spec',
    mime: 'text/x-rpm-spec',
    mode: 'rpm',
    ext: ['spec'],
  },
  spec: {
    langName: 'RPM Spec',
    mime: 'text/x-rpm-spec',
    mode: 'rpm',
    ext: ['spec'],
  },
  ruby: {
    langName: 'Ruby',
    weight: 16,
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  rb: {
    langName: 'Ruby',
    weight: 16,
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  jruby: {
    langName: 'Ruby',
    weight: 16,
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  macruby: {
    langName: 'Ruby',
    weight: 16,
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  rake: {
    langName: 'Ruby',
    weight: 16,
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  rbx: {
    langName: 'Ruby',
    weight: 16,
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  rust: {
    langName: 'Rust',
    weight: 16,
    mime: 'text/x-rustsrc',
    mode: 'rust',
    ext: ['rs'],
  },
  rs: {
    langName: 'Rust',
    weight: 16,
    mime: 'text/x-rustsrc',
    mode: 'rust',
    ext: ['rs'],
  },
  sas: { langName: 'SAS', mime: 'text/x-sas', mode: 'sas', ext: ['sas'] },
  sass: { langName: 'Sass', mime: 'text/x-sass', mode: 'sass', ext: ['sass'] },
  scala: {
    langName: 'Scala',
    mime: 'text/x-scala',
    mode: 'clike',
    ext: ['scala'],
  },
  scheme: {
    langName: 'Scheme',
    mime: 'text/x-scheme',
    mode: 'scheme',
    ext: ['scm', 'ss'],
  },
  scm: {
    langName: 'Scheme',
    mime: 'text/x-scheme',
    mode: 'scheme',
    ext: ['scm', 'ss'],
  },
  ss: {
    langName: 'Scheme',
    mime: 'text/x-scheme',
    mode: 'scheme',
    ext: ['scm', 'ss'],
  },
  shell: {
    langName: 'Shell',
    weight: 17,
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
  },
  sh: {
    langName: 'Shell',
    weight: 17,
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
  },
  ksh: {
    langName: 'Shell',
    weight: 17,
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
  },
  bash: {
    langName: 'Shell',
    weight: 17,
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
  },
  zsh: {
    langName: 'Shell',
    weight: 17,
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
  },
  sieve: {
    langName: 'Sieve',
    mime: 'application/sieve',
    mode: 'sieve',
    ext: ['siv', 'sieve'],
  },
  siv: {
    langName: 'Sieve',
    mime: 'application/sieve',
    mode: 'sieve',
    ext: ['siv', 'sieve'],
  },
  slim: {
    langName: 'Slim',
    mimes: ['text/x-slim', 'application/x-slim'],
    mode: 'slim',
    ext: ['slim'],
  },
  smalltalk: {
    langName: 'Smalltalk',
    mime: 'text/x-stsrc',
    mode: 'smalltalk',
    ext: ['st'],
  },
  st: {
    langName: 'Smalltalk',
    mime: 'text/x-stsrc',
    mode: 'smalltalk',
    ext: ['st'],
  },
  smarty: {
    langName: 'Smarty',
    mime: 'text/x-smarty',
    mode: 'smarty',
    ext: ['tpl'],
  },
  tpl: {
    langName: 'Smarty',
    mime: 'text/x-smarty',
    mode: 'smarty',
    ext: ['tpl'],
  },
  solr: { langName: 'Solr', mime: 'text/x-solr', mode: 'solr' },
  sml: {
    langName: 'SML',
    mime: 'text/x-sml',
    mode: 'mllike',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  fun: {
    langName: 'SML',
    mime: 'text/x-sml',
    mode: 'mllike',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  smackspec: {
    langName: 'SML',
    mime: 'text/x-sml',
    mode: 'mllike',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  soy: {
    langName: 'Soy',
    mime: 'text/x-soy',
    mode: 'soy',
    ext: ['soy'],
    alias: ['closure template'],
  },
  'closure template': {
    langName: 'Soy',
    mime: 'text/x-soy',
    mode: 'soy',
    ext: ['soy'],
    alias: ['closure template'],
  },
  sparql: {
    langName: 'SPARQL',
    mime: 'application/sparql-query',
    mode: 'sparql',
    ext: ['rq', 'sparql'],
    alias: ['sparul'],
  },
  rq: {
    langName: 'SPARQL',
    mime: 'application/sparql-query',
    mode: 'sparql',
    ext: ['rq', 'sparql'],
    alias: ['sparul'],
  },
  sparul: {
    langName: 'SPARQL',
    mime: 'application/sparql-query',
    mode: 'sparql',
    ext: ['rq', 'sparql'],
    alias: ['sparul'],
  },
  spreadsheet: {
    langName: 'Spreadsheet',
    mime: 'text/x-spreadsheet',
    mode: 'spreadsheet',
    alias: ['excel', 'formula'],
  },
  excel: {
    langName: 'Spreadsheet',
    mime: 'text/x-spreadsheet',
    mode: 'spreadsheet',
    alias: ['excel', 'formula'],
  },
  formula: {
    langName: 'Spreadsheet',
    mime: 'text/x-spreadsheet',
    mode: 'spreadsheet',
    alias: ['excel', 'formula'],
  },
  sqlite: { langName: 'SQLite', mime: 'text/x-sqlite', mode: 'sql' },
  squirrel: {
    langName: 'Squirrel',
    mime: 'text/x-squirrel',
    mode: 'clike',
    ext: ['nut'],
  },
  nut: {
    langName: 'Squirrel',
    mime: 'text/x-squirrel',
    mode: 'clike',
    ext: ['nut'],
  },
  stylus: {
    langName: 'Stylus',
    mime: 'text/x-styl',
    mode: 'stylus',
    ext: ['styl'],
  },
  styl: {
    langName: 'Stylus',
    mime: 'text/x-styl',
    mode: 'stylus',
    ext: ['styl'],
  },
  swift: {
    langName: 'Swift',
    mime: 'text/x-swift',
    mode: 'swift',
    ext: ['swift'],
  },
  stex: {
    langName: 'LaTeX',
    weight: 10,
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  latex: {
    langName: 'LaTeX',
    weight: 10,
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  ltx: {
    langName: 'LaTeX',
    weight: 10,
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  tex: {
    langName: 'LaTeX',
    weight: 10,
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  systemverilog: {
    langName: 'SystemVerilog',
    mime: 'text/x-systemverilog',
    mode: 'verilog',
    ext: ['v', 'sv', 'svh'],
  },
  verilog: {
    langName: 'Verilog',
    mime: 'text/x-verilog',
    mode: 'verilog',
    ext: ['v'],
  },
  v: {
    langName: 'Verilog',
    mime: 'text/x-verilog',
    mode: 'verilog',
    ext: ['v'],
  },
  sv: {
    langName: 'SystemVerilog',
    mime: 'text/x-systemverilog',
    mode: 'verilog',
    ext: ['v', 'sv', 'svh'],
  },
  svh: {
    langName: 'SystemVerilog',
    mime: 'text/x-systemverilog',
    mode: 'verilog',
    ext: ['v', 'sv', 'svh'],
  },
  tcl: { langName: 'Tcl', mime: 'text/x-tcl', mode: 'tcl', ext: ['tcl'] },
  textile: {
    langName: 'Textile',
    mime: 'text/x-textile',
    mode: 'textile',
    ext: ['textile'],
  },
  tiddlywiki: {
    langName: 'TiddlyWiki',
    mime: 'text/x-tiddlywiki',
    mode: 'tiddlywiki',
  },
  'tiki wiki': { langName: 'Tiki wiki', mime: 'text/tiki', mode: 'tiki' },
  tiki: { langName: 'Tiki wiki', mime: 'text/tiki', mode: 'tiki' },
  toml: { langName: 'TOML', mime: 'text/x-toml', mode: 'toml', ext: ['toml'] },
  tornado: { langName: 'Tornado', mime: 'text/x-tornado', mode: 'tornado' },
  troff: {
    langName: 'troff',
    mime: 'text/troff',
    mode: 'troff',
    ext: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
  },
  ttcn: {
    langName: 'TTCN',
    mime: 'text/x-ttcn',
    mode: 'ttcn',
    ext: ['ttcn', 'ttcn3', 'ttcnpp'],
  },
  ttcn3: {
    langName: 'TTCN',
    mime: 'text/x-ttcn',
    mode: 'ttcn',
    ext: ['ttcn', 'ttcn3', 'ttcnpp'],
  },
  ttcnpp: {
    langName: 'TTCN',
    mime: 'text/x-ttcn',
    mode: 'ttcn',
    ext: ['ttcn', 'ttcn3', 'ttcnpp'],
  },
  ttcn_cfg: {
    langName: 'TTCN_CFG',
    mime: 'text/x-ttcn-cfg',
    mode: 'ttcn-cfg',
    ext: ['cfg'],
  },
  'ttcn-cfg': {
    langName: 'TTCN_CFG',
    mime: 'text/x-ttcn-cfg',
    mode: 'ttcn-cfg',
    ext: ['cfg'],
  },
  cfg: {
    langName: 'TTCN_CFG',
    mime: 'text/x-ttcn-cfg',
    mode: 'ttcn-cfg',
    ext: ['cfg'],
  },
  turtle: {
    langName: 'Turtle',
    mime: 'text/turtle',
    mode: 'turtle',
    ext: ['ttl'],
  },
  ttl: {
    langName: 'Turtle',
    mime: 'text/turtle',
    mode: 'turtle',
    ext: ['ttl'],
  },
  typescript: {
    langName: 'TypeScript',
    weight: 10,
    mime: 'application/typescript',
    mode: 'javascript',
    ext: ['ts'],
    alias: ['ts'],
  },
  ts: {
    langName: 'TypeScript',
    weight: 10,
    mime: 'application/typescript',
    mode: 'javascript',
    ext: ['ts'],
    alias: ['ts'],
  },
  'typescript-jsx': {
    langName: 'TypeScript-JSX',
    mime: 'text/typescript-jsx',
    mode: 'jsx',
    ext: ['tsx'],
    alias: ['tsx'],
  },
  tsx: {
    langName: 'TypeScript-JSX',
    mime: 'text/typescript-jsx',
    mode: 'jsx',
    ext: ['tsx'],
    alias: ['tsx'],
  },
  twig: { langName: 'Twig', mime: 'text/x-twig', mode: 'twig' },
  'web idl': {
    langName: 'Web IDL',
    mime: 'text/x-webidl',
    mode: 'webidl',
    ext: ['webidl'],
  },
  webidl: {
    langName: 'Web IDL',
    mime: 'text/x-webidl',
    mode: 'webidl',
    ext: ['webidl'],
  },
  'vb.net': { langName: 'VB.NET', mime: 'text/x-vb', mode: 'vb', ext: ['vb'] },
  vb: { langName: 'VB.NET', mime: 'text/x-vb', mode: 'vb', ext: ['vb'] },
  vbscript: {
    langName: 'VBScript',
    mime: 'text/vbscript',
    mode: 'vbscript',
    ext: ['vbs'],
  },
  vbs: {
    langName: 'VBScript',
    mime: 'text/vbscript',
    mode: 'vbscript',
    ext: ['vbs'],
  },
  velocity: {
    langName: 'Velocity',
    mime: 'text/velocity',
    mode: 'velocity',
    ext: ['vtl'],
  },
  vtl: {
    langName: 'Velocity',
    mime: 'text/velocity',
    mode: 'velocity',
    ext: ['vtl'],
  },
  vhdl: {
    langName: 'VHDL',
    mime: 'text/x-vhdl',
    mode: 'vhdl',
    ext: ['vhd', 'vhdl'],
  },
  vhd: {
    langName: 'VHDL',
    mime: 'text/x-vhdl',
    mode: 'vhdl',
    ext: ['vhd', 'vhdl'],
  },
  'vue.js component': {
    langName: 'Vue.js Component',
    mimes: ['script/x-vue', 'text/x-vue'],
    mode: 'vue',
    ext: ['vue'],
  },
  vue: {
    langName: 'Vue.js Component',
    mimes: ['script/x-vue', 'text/x-vue'],
    mode: 'vue',
    ext: ['vue'],
  },
  xml: {
    langName: 'XML',
    weight: 10,
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  xsl: {
    langName: 'XML',
    weight: 10,
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  xsd: {
    langName: 'XML',
    weight: 10,
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  svg: {
    langName: 'XML',
    weight: 10,
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  rss: {
    langName: 'XML',
    weight: 10,
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  wsdl: {
    langName: 'XML',
    weight: 10,
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  xquery: {
    langName: 'XQuery',
    mime: 'application/xquery',
    mode: 'xquery',
    ext: ['xy', 'xquery'],
  },
  xy: {
    langName: 'XQuery',
    mime: 'application/xquery',
    mode: 'xquery',
    ext: ['xy', 'xquery'],
  },
  yacas: {
    langName: 'Yacas',
    mime: 'text/x-yacas',
    mode: 'yacas',
    ext: ['ys'],
  },
  ys: { langName: 'Yacas', mime: 'text/x-yacas', mode: 'yacas', ext: ['ys'] },
  yaml: {
    langName: 'YAML',
    mimes: ['text/x-yaml', 'text/yaml'],
    mode: 'yaml',
    ext: ['yaml', 'yml'],
    alias: ['yml'],
  },
  yml: {
    langName: 'YAML',
    mimes: ['text/x-yaml', 'text/yaml'],
    mode: 'yaml',
    ext: ['yaml', 'yml'],
    alias: ['yml'],
  },
  z80: { langName: 'Z80', mime: 'text/x-z80', mode: 'z80', ext: ['z80'] },
  mscgen: {
    langName: 'msgenny',
    mime: 'text/x-msgenny',
    mode: 'mscgen',
    ext: ['msgenny'],
  },
  mscin: {
    langName: 'mscgen',
    mime: 'text/x-mscgen',
    mode: 'mscgen',
    ext: ['mscgen', 'mscin', 'msc'],
  },
  msc: {
    langName: 'mscgen',
    mime: 'text/x-mscgen',
    mode: 'mscgen',
    ext: ['mscgen', 'mscin', 'msc'],
  },
  xu: { langName: 'xu', mime: 'text/x-xu', mode: 'mscgen', ext: ['xu'] },
  msgenny: {
    langName: 'msgenny',
    mime: 'text/x-msgenny',
    mode: 'mscgen',
    ext: ['msgenny'],
  },
  webassembly: {
    langName: 'WebAssembly',
    mime: 'text/webassembly',
    mode: 'wast',
    ext: ['wat', 'wast'],
  },
  wast: {
    langName: 'WebAssembly',
    mime: 'text/webassembly',
    mode: 'wast',
    ext: ['wat', 'wast'],
  },
  wat: {
    langName: 'WebAssembly',
    mime: 'text/webassembly',
    mode: 'wast',
    ext: ['wat', 'wast'],
  },
} as {
  [key: string]: {
    langName: string
    mime?: string
    mimes?: string[]
    mode: string
    ext?: string[]
    alias?: string[]
    weight?: number
  }
}

export type LangMode = string
